# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='SleepIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='StepsIntervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
            ],
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name': 'Steps'},
        ),
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepsintervals',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Steps'),
        ),
        migrations.AddField(
            model_name='sleepintervals',
            name='sleep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Sleep'),
        ),
        migrations.AddField(
            model_name='positionintervals',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Position'),
        ),
    ]
