# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170620_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionintervals',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='sleepintervals',
            name='sleep',
        ),
        migrations.RemoveField(
            model_name='stepsintervals',
            name='steps',
        ),
        migrations.AddField(
            model_name='position',
            name='end',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='position',
            name='start',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='end',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='start',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='end',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='steps',
            name='start',
            field=models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PositionIntervals',
        ),
        migrations.DeleteModel(
            name='SleepIntervals',
        ),
        migrations.DeleteModel(
            name='StepsIntervals',
        ),
    ]
